[project]
name = "ai-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.5",
    "fastapi>=0.135.1",
    "google-cloud-vision>=3.12.1",
    "google-genai>=1.67.0",
    "langchain>=1.2.12",
    "langchain-chroma>=1.0.0",
    "langchain-classic>=1.0.0",
    "langchain-google-genai>=3.1.0",
    "langchain-google-vertexai>=2.1.0",
    "langchain-text-splitters>=1.0.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.1",
    "pydantic>=2.12.5",
    "python-multipart>=0.0.20",
    "pytesseract>=0.3.13",
    "rank-bm25>=0.2.2",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.3.0",
    "transformers>=5.3.0",
    "uvicorn>=0.42.0",
]
