"""add submission_feedback table

Revision ID: 10f48ae062ac
Revises: 8381ea591b5d
Create Date: 2026-03-11 22:57:28.721984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '10f48ae062ac'
down_revision: Union[str, None] = '8381ea591b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_feedback',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('overall_feedback', sa.Text(), nullable=False),
    sa.Column('step_by_step_corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failed_at_step', sa.String(length=255), nullable=True),
    sa.Column('rag_chunks_used', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('knowledge_gap_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.UniqueConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_feedback')
    # ### end Alembic commands ###

