"""add submission table

Revision ID: 137827d27bec
Revises: 54887631d9ee
Create Date: 2026-03-11 22:56:07.645592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137827d27bec'
down_revision: Union[str, None] = '54887631d9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('image_quality_score', sa.Float(), nullable=True),
    sa.Column('quality_rejection_reason', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Enum('QUEUED', 'OCR', 'GRADING', 'DONE', 'REJECTED', name='submission_processing_status'), nullable=False),
    sa.Column('grade_classification', sa.Enum('CORRECT', 'PARTIAL', 'INCORRECT', name='grade_classification'), nullable=True),
    sa.Column('score_percentage', sa.Float(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_exam_submission', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index('ix_submissions_student_submitted', 'submissions', ['student_id', 'submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submissions_student_submitted', table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###

