"""add qr_sessions table

Revision ID: 2d9bea4cf8f7
Revises: d193aed70873
Create Date: 2026-03-11 22:43:15.025371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9bea4cf8f7'
down_revision: Union[str, None] = 'd193aed70873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_sessions',
    sa.Column('qr_session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('qr_code_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCANNED', 'AUTHENTICATED', 'EXPIRED', name='qr_session_status'), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('qr_session_id'),
    sa.UniqueConstraint('qr_code_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_sessions')
    # ### end Alembic commands ###

