"""add quiz_attempt table

Revision ID: 308aa7ee926e
Revises: 356f56407ca1
Create Date: 2026-03-11 23:03:51.460894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308aa7ee926e'
down_revision: Union[str, None] = '356f56407ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.question_id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['micro_quizzes.quiz_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index('ix_quiz_attempts_lookup', 'quiz_attempts', ['quiz_id', 'student_id', 'question_id', 'attempt_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quiz_attempts_lookup', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###

