"""add micro_quiz table

Revision ID: 5125ff73154a
Revises: 6a5df2e3f032
Create Date: 2026-03-11 22:59:18.394100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5125ff73154a'
down_revision: Union[str, None] = '6a5df2e3f032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_quizzes',
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('gap_id', sa.UUID(), nullable=True),
    sa.Column('concept_targeted', sa.String(length=255), nullable=False),
    sa.Column('total_questions', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', name='micro_quiz_status'), server_default='ASSIGNED', nullable=False),
    sa.Column('score_percentage', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['knowledge_gaps.gap_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('micro_quizzes')
    # ### end Alembic commands ###

