"""add student_personal_note table

Revision ID: 54887631d9ee
Revises: 00253b4af117
Create Date: 2026-03-11 22:55:40.832526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54887631d9ee'
down_revision: Union[str, None] = '00253b4af117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_personal_notes',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BIGINT(), nullable=True),
    sa.Column('chroma_collection_id', sa.String(length=100), nullable=True),
    sa.Column('embedding_status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='student_note_embedding_status'), server_default='PENDING', nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_personal_notes')
    # ### end Alembic commands ###

