"""add student_progress table

Revision ID: 561f577087ec
Revises: e5b4afd8c19f
Create Date: 2026-03-11 23:04:36.760657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561f577087ec'
down_revision: Union[str, None] = 'e5b4afd8c19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_progress',
    sa.Column('progress_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('WEEKLY', 'MONTHLY', name='period_type'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('submission_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('gap_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_at_risk', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('progress_id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'period_type', 'period_start', name='uq_student_progress')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_progress')
    # ### end Alembic commands ###

