"""add curriculum_document table

Revision ID: 5c5e10bd3b14
Revises: 988a700937bf
Create Date: 2026-03-11 22:53:46.952367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5e10bd3b14'
down_revision: Union[str, None] = '988a700937bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_documents',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BIGINT(), nullable=True),
    sa.Column('doc_type', sa.Enum('CURRICULUM_PDF', 'INSTRUCTOR_NOTE', name='document_type'), nullable=False),
    sa.Column('embedding_status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='embedding_status'), server_default='PENDING', nullable=False),
    sa.Column('chroma_collection_id', sa.String(length=100), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curriculum_documents')
    # ### end Alembic commands ###

