"""add grade table

Revision ID: 6393f2c09201
Revises: 040651f54dfc
Create Date: 2026-03-11 22:50:56.213988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6393f2c09201'
down_revision: Union[str, None] = '040651f54dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('grade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade_name', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('grade_id'),
    sa.UniqueConstraint('grade_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    # ### end Alembic commands ###

