"""add knowledge_gap table

Revision ID: 6a5df2e3f032
Revises: 10f48ae062ac
Create Date: 2026-03-11 22:58:53.906684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5df2e3f032'
down_revision: Union[str, None] = '10f48ae062ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_gaps',
    sa.Column('gap_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('concept_name', sa.String(length=255), nullable=False),
    sa.Column('topic_tag', sa.String(length=100), nullable=False),
    sa.Column('recurrence_count', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('gap_id'),
    sa.UniqueConstraint('student_id', 'topic_tag', name='uq_knowledge_gap_student_topic')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_gaps')
    # ### end Alembic commands ###

