"""add ocr_log table

Revision ID: 8381ea591b5d
Revises: 137827d27bec
Create Date: 2026-03-11 22:56:35.502447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8381ea591b5d'
down_revision: Union[str, None] = '137827d27bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_logs',
    sa.Column('ocr_log_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('engine_used', sa.String(length=50), nullable=False),
    sa.Column('raw_extracted_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('preprocessing_steps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('ocr_log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_logs')
    # ### end Alembic commands ###

