"""add_feedback_override_fields

Revision ID: ddd6518d2c95
Revises: fcbc023fa35e
Create Date: 2026-03-30 16:25:03.402040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd6518d2c95'
down_revision: Union[str, None] = 'fcbc023fa35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_feedback', sa.Column('score_percentage', sa.Float(), nullable=True))
    op.add_column('submission_feedback', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('submission_feedback', sa.Column('improvements', sa.Text(), nullable=True))
    op.add_column('submission_feedback', sa.Column('instructor_comments', sa.Text(), nullable=True))
    op.add_column('submission_feedback', sa.Column('graded_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'submission_feedback', 'users', ['graded_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission_feedback', type_='foreignkey')
    op.drop_column('submission_feedback', 'graded_by')
    op.drop_column('submission_feedback', 'instructor_comments')
    op.drop_column('submission_feedback', 'improvements')
    op.drop_column('submission_feedback', 'strengths')
    op.drop_column('submission_feedback', 'score_percentage')
    # ### end Alembic commands ###

