"""add concept_heatmap_entry table

Revision ID: e5b4afd8c19f
Revises: 308aa7ee926e
Create Date: 2026-03-11 23:04:14.263348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b4afd8c19f'
down_revision: Union[str, None] = '308aa7ee926e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_heatmap_entries',
    sa.Column('heatmap_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('concept_name', sa.String(length=255), nullable=False),
    sa.Column('topic_tag', sa.String(length=100), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('affected_student_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('heatmap_id'),
    sa.UniqueConstraint('subject_id', 'topic_tag', name='uq_heatmap_subject_topic')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_heatmap_entries')
    # ### end Alembic commands ###

