"""add academic tables

Revision ID: e9948f0c861e
Revises: 6ba4779ea1a9
Create Date: 2026-03-11 22:13:37.934096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9948f0c861e'
down_revision: Union[str, None] = '6ba4779ea1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('grade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade_name', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('grade_id'),
    sa.UniqueConstraint('grade_name')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('chroma_namespace', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('chroma_namespace'),
    sa.UniqueConstraint('subject_code')
    )
    op.create_table('instructor_subjects',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('instructor_id', 'subject_id', name='uq_instructor_subject')
    )
    op.create_table('student_enrollments',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id'),
    sa.UniqueConstraint('student_id', 'grade_id', 'subject_id', name='uq_student_enrollment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_enrollments')
    op.drop_table('instructor_subjects')
    op.drop_table('subjects')
    op.drop_table('grades')
    # ### end Alembic commands ###

