"""add sensor_log table

Revision ID: ea4569f54b95
Revises: fba7689c388b
Create Date: 2026-03-11 23:06:40.923015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4569f54b95'
down_revision: Union[str, None] = 'fba7689c388b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('sensor_type', sa.String(length=20), nullable=False),
    sa.Column('ldr_value', sa.Float(), nullable=True),
    sa.Column('distance_cm', sa.Float(), nullable=True),
    sa.Column('led_activated', sa.Boolean(), nullable=True),
    sa.Column('alert_triggered', sa.Enum('POSTURE', 'ABSENCE', 'EXAM_PAUSE', name='alert_triggered'), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['iot_devices.device_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_logs')
    # ### end Alembic commands ###

