"""add iot_device table

Revision ID: fba7689c388b
Revises: 561f577087ec
Create Date: 2026-03-11 23:05:17.703016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fba7689c388b'
down_revision: Union[str, None] = '561f577087ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_devices',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('assigned_student_id', sa.UUID(), nullable=True),
    sa.Column('device_mac', postgresql.MACADDR(), nullable=False),
    sa.Column('device_label', sa.String(length=100), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('mqtt_topic_prefix', sa.String(length=150), nullable=False),
    sa.Column('firmware_version', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip_address', postgresql.INET(), nullable=True),
    sa.Column('registered_by', sa.UUID(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['assigned_student_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('device_mac'),
    sa.UniqueConstraint('mqtt_topic_prefix')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iot_devices')
    # ### end Alembic commands ###

