"""add_max_score_to_assignments

Revision ID: fcbc023fa35e
Revises: 5051ee1a3269
Create Date: 2026-03-30 16:03:16.120457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbc023fa35e'
down_revision: Union[str, None] = '5051ee1a3269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('max_score', sa.Float(), server_default='100.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'max_score')
    # ### end Alembic commands ###

