#ifndef CONFIG_H
#define CONFIG_H

#define WIFI_SSID "heavenyard_2"
#define WIFI_PASSWORD "CLB4041D64"

#define MQTT_BROKER "192.168.1.89"
#define MQTT_PORT 1883
#define MQTT_USER ""
#define MQTT_PASSWORD ""

#define DEVICE_ID "ESP32-Aayush"
#define DEVICE_API_KEY "nvGSe-iFXcYo5Ze-5ismzRLcHMaznFFarMVG_iIsHic"
#define FIRMWARE_VERSION "0.2.0"

#define TOPIC_LIGHT "gyanavriksha/devices/" DEVICE_ID "/sensors/light"
#define TOPIC_DISTANCE "gyanavriksha/devices/" DEVICE_ID "/sensors/distance"
#define TOPIC_STATUS "gyanavriksha/devices/" DEVICE_ID "/status"
#define TOPIC_LED_CMD "gyanavriksha/devices/" DEVICE_ID "/commands/led"

#define LDR_PIN 13
#define LDR_USE_DIGITAL_OUTPUT true
#define LDR_DO_DARK_STATE HIGH
#define LED_PIN 2
#define ULTRASONIC_TRIG 5
#define ULTRASONIC_ECHO 18

#define LDR_BUCKET_DIM_MAX 1200
#define LDR_BUCKET_NORMAL_MAX 2600
#define LDR_BUCKET_BRIGHT_MAX 4095
#define LDR_LED_ON_THRESHOLD 1000
#define LDR_LED_OFF_THRESHOLD 1400
#define LED_MANUAL_OVERRIDE_MS 30000

#define DISTANCE_TOO_CLOSE_CM 30.0f
#define DISTANCE_PRESENT_MAX_CM 150.0f
#define DISTANCE_VALID_MIN_CM 2.0f
#define DISTANCE_VALID_MAX_CM 400.0f
#define DISTANCE_ALERT_WINDOW_MS 8000
#define DISTANCE_FILTER_WINDOW 5
#define DISTANCE_AWAY_SUSTAIN_MS 6000
#define DISTANCE_TOO_CLOSE_SUSTAIN_MS 4000
#define DISTANCE_EVENT_COOLDOWN_MS 15000

#define SENSOR_READ_INTERVAL 1000
#define MQTT_PUBLISH_INTERVAL 5000
#define MQTT_HEARTBEAT_INTERVAL 10000
#define SENSOR_BOOT_SAMPLE_COUNT 5
#define WIFI_CONNECT_TIMEOUT_MS 20000
#define WIFI_RETRY_INTERVAL_MS 10000
#define MQTT_RECONNECT_BASE_MS 2000
#define MQTT_RECONNECT_MAX_MS 30000

#endif